### ISSUE TITLE
Navigation - Thoughts

### ISSUE THREAD

**Issue by LefterisXris** [LefterisXris/CodeTour#12]
Playing a `Trailer` should support (plugin's toolbar):
- [ ] Show total number of steps
- [ ] Show progress (e.g. current step like 5/20 - 25%)
- [ ] Go to previous and next step (buttons &larr; and &rarr;)
- [ ] Return to current step point (if user manually scrolled somewhere else)

Within the code, we should support:
- [ ] Add (inline) any extra assets e.g. comments, links, images, .gifs, sound

**Comment by LefterisXris** [comment]
Will continue on #22
